export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const SET_MOVIES_QUERY = 'SET_MOVIES_QUERY';
export const SET_MOVIES_SORT_BY = 'SET_MOVIES_SORT_BY';
export const SET_MOVIES_SEARCH_BY = 'SET_MOVIES_SEARCH_BY';