export const FETCH_MOVIE_BY_ID_REQUEST = 'FETCH_MOVIE_BY_ID_REQUEST';
export const FETCH_MOVIE_BY_ID_FAILURE = 'FETCH_MOVIE_BY_ID_FAILURE';
export const FETCH_MOVIE_BY_ID_SUCCESS = 'FETCH_MOVIE_BY_ID_SUCCESS';
export const FETCH_MOVIES_BY_GENRES_REQUEST = 'FETCH_MOVIES_BY_GENRES_REQUEST';
export const FETCH_MOVIES_BY_GENRES_FAILURE = 'FETCH_MOVIES_BY_GENRES_FAILURE';
export const FETCH_MOVIES_BY_GENRES_SUCCESS = 'FETCH_MOVIES_BY_GENRES_SUCCESS';
